Update hblock to 3.4.3

diff --git a/hblock b/hblock
--- a/hblock
+++ b/hblock
@@ -4,7 +4,7 @@ set -eu
 export LC_ALL='C'
 
 # Metadata.
-if [ -z "${HOSTS_VERSION+x}"    ]; then HOSTS_VERSION='3.4.2'; fi
+if [ -z "${HOSTS_VERSION+x}"    ]; then HOSTS_VERSION='3.4.3'; fi
 if [ -z "${HOSTS_AUTHOR+x}"     ]; then HOSTS_AUTHOR='FLOSSbOxIN <dev@flossboxin.org.in>'; fi
 if [ -z "${HOSTS_LICENSE+x}"    ]; then HOSTS_LICENSE='MIT, https://opensource.org/licenses/MIT'; fi
 if [ -z "${HOSTS_REPOSITORY+x}" ]; then HOSTS_REPOSITORY='https://github.com/vdbhb59/hosts/blob/master/hblock'; fi
@@ -16,9 +16,11 @@ if [ -n "${ZSH_VERSION-}" ]; then emulate -L ksh; fi
 if [ -z "${ETCDIR+x}" ]; then ETCDIR='/etc'; fi
 if [ -z "${XDG_CONFIG_HOME+x}" ]; then XDG_CONFIG_HOME="${HOME-}/.config"; fi
 
-# Remove temporary files on exit.
-cleanup() { ret="$?"; rm -rf -- "${TMPDIR:-${TMP:-/tmp}}/hblock.${$}."*; trap - EXIT; exit "${ret:?}"; }
-{ trap cleanup EXIT ||:; trap cleanup TERM ||:; trap cleanup INT ||:; trap cleanup HUP ||:; } 2>/dev/null
+# Trap various signals to remove temporary files on exit.
+abort() { : "${EXIT_STATUS:=${?}}"; rm -rf -- "${TMPDIR:-${TMP:-/tmp}}/hblock.${$}."*; trap - EXIT; exit "${EXIT_STATUS:?}"; }
+{ trap abort EXIT ||:; trap abort TERM ||:; trap abort INT ||:; trap abort HUP ||:; } 2>/dev/null
+# For all other signals the exit status is preserved, but USR1 and USR2 will always use 10 and 12 respectively.
+{ trap 'EXIT_STATUS=10; abort' USR1; trap 'EXIT_STATUS=12; abort' USR2; } 2>/dev/null
 
 # Built-in header.
 HOSTNAME="${HOSTNAME-"$(uname -n)"}"
@@ -84,10 +86,12 @@ HBLOCK_SOURCES_BUILTIN="$(cat <<-'EOF'
 	https://raw.githubusercontent.com/hectorm/hmirror/master/data/ublock-2021/list.txt
 	https://raw.githubusercontent.com/hectorm/hmirror/master/data/ublock-2022/list.txt
 	https://raw.githubusercontent.com/hectorm/hmirror/master/data/ublock-2023/list.txt
+	https://raw.githubusercontent.com/hectorm/hmirror/master/data/ublock-2024/list.txt
 	https://raw.githubusercontent.com/hectorm/hmirror/master/data/ublock-abuse/list.txt
 	https://raw.githubusercontent.com/hectorm/hmirror/master/data/ublock-badware/list.txt
 	https://raw.githubusercontent.com/hectorm/hmirror/master/data/ublock-privacy/list.txt
 	https://raw.githubusercontent.com/hectorm/hmirror/master/data/urlhaus/list.txt
+	https://raw.githubusercontent.com/hectorm/hmirror/master/data/usom.gov.tr/list.txt
 	https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt
 	https://www.apps2sd.info/idm/filters.txt
 	https://filters.adtidy.org/windows/filters/1.txt?id=1
@@ -850,7 +854,7 @@ main() {
 			sourceDlFile="${sourcesDlDir:?}"/"$(rand)"
 			touch -- "${sourceDlFile:?}.part"
 			{
-				if fetchUrl "${url:?}" > "${sourceDlFile:?}.part"; then
+				if { fetchUrl "${url:?}" && printf '\n'; } > "${sourceDlFile:?}.part"; then
 					if [ -e "${sourceDlFile:?}.part" ]; then
 						printf '\n' >> "${sourceDlFile:?}.part"
 						mv -- "${sourceDlFile:?}.part" "${sourceDlFile:?}"
@@ -861,7 +865,7 @@ main() {
 						printWarn "Cannot obtain source: ${url:?}"
 					else
 						printError "Cannot obtain source: ${url:?}"
-						{ kill "${$}"; exit 1; } 2>/dev/null
+						{ kill -s USR2 "${$}"; exit 1; } 2>/dev/null
 					fi
 				fi
 			} &
